version: '3'
services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    networks:
      - my-network
  
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    networks:
      - my-network
  
  owner-service:
    build: ./owner-service
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
      - RABBITMQ_URI=amqp://rabbitmq:5672
      - MONGO_URI=mongodb://mongodb:27017/crimmitdb
    depends_on:
      - rabbitmq
      - mongodb
    networks:
      - my-network
    volumes:
      - ./owner-service:/app
    command: npm run start:dev

  product-service:
    build: ./product-service
    ports:
      - "3002:3002"
    environment:
      - NODE_ENV=development
      - RABBITMQ_URI=amqp://rabbitmq:5672
      - MONGO_URI=mongodb://mongodb:27017/crimmitdb
    depends_on:
      - rabbitmq
      - mongodb
    networks:
      - my-network
    volumes:
      - ./product-service:/app
      - ./product-service:/proto
    command: npm run start:dev

  order-service:
    build: ./order-service
    ports:
      - "3003:3003"
    environment:
      - NODE_ENV=development
      - MONGO_URI=mongodb://mongodb:27017/crimmitdb
    depends_on:
      - mongodb
    networks:
      - my-network
    volumes:
      - ./order-service:/app
      - ./order-service:/proto
    command: npm run start:dev

networks:
  my-network:
    driver: bridge
